project_id = "slfexlrcfiooqwbmiudz"

[api]
enabled = true
port = 54321
schemas = ["public", "storage", "graphql_public"]

[functions.waiting-queue]
enabled = true
verify_jwt = true
import_map = "./functions/waiting-queue/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/waiting-queue/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/waiting-queue/*.html" ]

[functions.accept-slot]
enabled = true
verify_jwt = true
import_map = "./functions/accept-slot/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/accept-slot/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/accept-slot/*.html" ]
