name: padelpush
description: "PadelPush - UI base"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_maps_flutter: ^2.14.0
  go_router: ^7.0.1
  flutter_animate: ^4.0.0
  url_launcher: ^6.1.7
  provider: ^6.0.5
  shared_preferences: ^2.2.2
  supabase_flutter: ^2.10.2
  intl: ^0.19.0
  http: ^0.13.6
  firebase_core: ^3.0.0
  firebase_messaging: ^15.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_launcher_icons: ^0.14.0

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/map_style.json

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"
